cache:
    directories:
        - /tmp/cached/

before_install:
    - openssl aes-256-cbc -K $encrypted_766aa190bafb_key -iv $encrypted_766aa190bafb_iv -in deploy-key.enc -out deploy-key -d
    - chmod 600 deploy-key
    - mv deploy-key ~/.ssh/id_rsa

script: true

after_success:
    # Install Go and splitsh
    - eval "$(curl -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme | GIMME_GO_VERSION=1.4 bash)"
    - export GOPATH=$HOME/gopath
    - go get -d github.com/libgit2/git2go
    - cd $GOPATH/src/github.com/libgit2/git2go
    - git checkout next
    - git submodule update --init
    - make install
    - go get github.com/splitsh/lite
    - go build -o ~/bin/splitsh-lite github.com/splitsh/lite

    - cp /tmp/cached/splitsh.db .git/splitsh.db || true

    # Clone again to overcome limited cloning depth on Travis
    - git clone https://github.com/$TRAVIS_REPO_SLUG.git /tmp/ginger
    - cd /tmp/ginger

    - SHA1=`splitsh-lite --prefix=modules/mod_ginger_base/`
    - git push git@github.com:driebit/mod_ginger_base.git $SHA1:refs/heads/master

before_cache:
    - mv .git/splitsh.db /tmp/cached/
