language: erlang
otp_release:
    - 18.3

cache:
    directories:
        - /tmp/cached/

before_install:
    - openssl aes-256-cbc -K $encrypted_766aa190bafb_key -iv $encrypted_766aa190bafb_iv -in deploy-key.enc -out deploy-key -d
    - chmod 600 deploy-key
    - mv deploy-key ~/.ssh/id_rsa

script: true

deploy:
    provider: script
    script: scripts/split.sh
    on:
        all_branches: true
#        branch: master

before_cache:
    - mv .git/splitsh.db /tmp/cached/
