version: '2'

services:
    postgres:
        image: postgres:9.5
        environment:
            POSTGRES_USER: zotonic
        volumes:
            - ./data:/data
        working_dir: /data

    elasticsearch:
        image: elasticsearch:2.4
        ports:
            - 9200:9200

    logstash:
        image: logstash:2.4
        links:
            - elasticsearch
        command: -f /etc/logstash/json.conf
        volumes:
              - ./logstash/:/etc/logstash

    kibana:
        image: driebit/kibana-sense
        links:
            - elasticsearch
        ports:
            - 5601:5601

    zotonic:
        image: driebit/ginger-dev:0.x
        privileged: true
        links:
            - postgres
            - logstash
        volumes:
            - ./modules:/opt/zotonic/user/modules
            - ./sites:/opt/zotonic/user/sites
        ports:
            - 80:8000
        environment:
            MAKE: "true"
